language: ruby
rvm:
  - 2.0.0
before_deploy:
  - ./license_finder.sh
after_failure:
  - echo "--- License finder found un-approved licenses. ---"
after_success:
  - echo "--- All licenses have been approved. ---"
notifications:
  email:
    recipients:
    - matthew.larson@flukenetworks.com